version: '3.8'

networks:
  tempo:

volumes:
  database_data:
  cache_data:

services:
  app:
    container_name: tempo-bot
    environment:
      - SHELL=bash
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:helloworld@database/tempo
      - REDIS_URL=redis://cache:6379
    env_file:
      - .env
    networks:
      - tempo
    build:
      context: .
      dockerfile: apps/bot/Dockerfile

  database:
    image: timescale/timescaledb:latest-pg13
    container_name: tempo-db
    environment:
      POSTGRES_PASSWORD: helloworld
    networks:
      - tempo
    volumes:
      - database_data:/var/lib/postgresql/data
    restart: always

  cache:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    volumes:
      - cache_data:/data
    networks:
      - tempo
